/**
 * AUTO-GENERATED by bin/generate-fontsource-loaders.js — do not edit by hand.
 * Each loader returns concatenated CSS text (?inline) for host + canvas injection.
 */
export const fontsourceLoaders = {
    "inter": async () => {
        const modules = await Promise.all([
            import('@fontsource-variable/inter/wght.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "roboto": async () => {
        const modules = await Promise.all([
            import('@fontsource/roboto/latin-400.css?inline'),
            import('@fontsource/roboto/latin-500.css?inline'),
            import('@fontsource/roboto/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "open-sans": async () => {
        const modules = await Promise.all([
            import('@fontsource/open-sans/latin-400.css?inline'),
            import('@fontsource/open-sans/latin-600.css?inline'),
            import('@fontsource/open-sans/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "lato": async () => {
        const modules = await Promise.all([
            import('@fontsource/lato/latin-400.css?inline'),
            import('@fontsource/lato/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "montserrat": async () => {
        const modules = await Promise.all([
            import('@fontsource/montserrat/latin-400.css?inline'),
            import('@fontsource/montserrat/latin-500.css?inline'),
            import('@fontsource/montserrat/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "poppins": async () => {
        const modules = await Promise.all([
            import('@fontsource/poppins/latin-400.css?inline'),
            import('@fontsource/poppins/latin-500.css?inline'),
            import('@fontsource/poppins/latin-600.css?inline'),
            import('@fontsource/poppins/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "nunito": async () => {
        const modules = await Promise.all([
            import('@fontsource/nunito/latin-400.css?inline'),
            import('@fontsource/nunito/latin-600.css?inline'),
            import('@fontsource/nunito/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "raleway": async () => {
        const modules = await Promise.all([
            import('@fontsource/raleway/latin-400.css?inline'),
            import('@fontsource/raleway/latin-600.css?inline'),
            import('@fontsource/raleway/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "source-sans-3": async () => {
        const modules = await Promise.all([
            import('@fontsource/source-sans-3/latin-400.css?inline'),
            import('@fontsource/source-sans-3/latin-600.css?inline'),
            import('@fontsource/source-sans-3/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "work-sans": async () => {
        const modules = await Promise.all([
            import('@fontsource/work-sans/latin-400.css?inline'),
            import('@fontsource/work-sans/latin-600.css?inline'),
            import('@fontsource/work-sans/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "dm-sans": async () => {
        const modules = await Promise.all([
            import('@fontsource/dm-sans/latin-400.css?inline'),
            import('@fontsource/dm-sans/latin-500.css?inline'),
            import('@fontsource/dm-sans/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "manrope": async () => {
        const modules = await Promise.all([
            import('@fontsource/manrope/latin-400.css?inline'),
            import('@fontsource/manrope/latin-600.css?inline'),
            import('@fontsource/manrope/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "outfit": async () => {
        const modules = await Promise.all([
            import('@fontsource/outfit/latin-400.css?inline'),
            import('@fontsource/outfit/latin-600.css?inline'),
            import('@fontsource/outfit/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "plus-jakarta-sans": async () => {
        const modules = await Promise.all([
            import('@fontsource/plus-jakarta-sans/latin-400.css?inline'),
            import('@fontsource/plus-jakarta-sans/latin-500.css?inline'),
            import('@fontsource/plus-jakarta-sans/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "figtree": async () => {
        const modules = await Promise.all([
            import('@fontsource/figtree/latin-400.css?inline'),
            import('@fontsource/figtree/latin-600.css?inline'),
            import('@fontsource/figtree/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "instrument-sans": async () => {
        const modules = await Promise.all([
            import('@fontsource/instrument-sans/latin-400.css?inline'),
            import('@fontsource/instrument-sans/latin-500.css?inline'),
            import('@fontsource/instrument-sans/latin-600.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "rubik": async () => {
        const modules = await Promise.all([
            import('@fontsource/rubik/latin-400.css?inline'),
            import('@fontsource/rubik/latin-500.css?inline'),
            import('@fontsource/rubik/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "mulish": async () => {
        const modules = await Promise.all([
            import('@fontsource/mulish/latin-400.css?inline'),
            import('@fontsource/mulish/latin-600.css?inline'),
            import('@fontsource/mulish/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "karla": async () => {
        const modules = await Promise.all([
            import('@fontsource/karla/latin-400.css?inline'),
            import('@fontsource/karla/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "barlow": async () => {
        const modules = await Promise.all([
            import('@fontsource/barlow/latin-400.css?inline'),
            import('@fontsource/barlow/latin-600.css?inline'),
            import('@fontsource/barlow/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "ubuntu": async () => {
        const modules = await Promise.all([
            import('@fontsource/ubuntu/latin-400.css?inline'),
            import('@fontsource/ubuntu/latin-500.css?inline'),
            import('@fontsource/ubuntu/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "noto-sans": async () => {
        const modules = await Promise.all([
            import('@fontsource/noto-sans/latin-400.css?inline'),
            import('@fontsource/noto-sans/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "ibm-plex-sans": async () => {
        const modules = await Promise.all([
            import('@fontsource/ibm-plex-sans/latin-400.css?inline'),
            import('@fontsource/ibm-plex-sans/latin-500.css?inline'),
            import('@fontsource/ibm-plex-sans/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "space-grotesk": async () => {
        const modules = await Promise.all([
            import('@fontsource/space-grotesk/latin-400.css?inline'),
            import('@fontsource/space-grotesk/latin-500.css?inline'),
            import('@fontsource/space-grotesk/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "lexend": async () => {
        const modules = await Promise.all([
            import('@fontsource/lexend/latin-400.css?inline'),
            import('@fontsource/lexend/latin-600.css?inline'),
            import('@fontsource/lexend/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "albert-sans": async () => {
        const modules = await Promise.all([
            import('@fontsource/albert-sans/latin-400.css?inline'),
            import('@fontsource/albert-sans/latin-600.css?inline'),
            import('@fontsource/albert-sans/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "cabin": async () => {
        const modules = await Promise.all([
            import('@fontsource/cabin/latin-400.css?inline'),
            import('@fontsource/cabin/latin-500.css?inline'),
            import('@fontsource/cabin/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "josefin-sans": async () => {
        const modules = await Promise.all([
            import('@fontsource/josefin-sans/latin-400.css?inline'),
            import('@fontsource/josefin-sans/latin-600.css?inline'),
            import('@fontsource/josefin-sans/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "exo-2": async () => {
        const modules = await Promise.all([
            import('@fontsource/exo-2/latin-400.css?inline'),
            import('@fontsource/exo-2/latin-600.css?inline'),
            import('@fontsource/exo-2/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "red-hat-text": async () => {
        const modules = await Promise.all([
            import('@fontsource/red-hat-text/latin-400.css?inline'),
            import('@fontsource/red-hat-text/latin-500.css?inline'),
            import('@fontsource/red-hat-text/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "merriweather": async () => {
        const modules = await Promise.all([
            import('@fontsource/merriweather/latin-400.css?inline'),
            import('@fontsource/merriweather/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "playfair-display": async () => {
        const modules = await Promise.all([
            import('@fontsource/playfair-display/latin-400.css?inline'),
            import('@fontsource/playfair-display/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "lora": async () => {
        const modules = await Promise.all([
            import('@fontsource/lora/latin-400.css?inline'),
            import('@fontsource/lora/latin-600.css?inline'),
            import('@fontsource/lora/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "source-serif-4": async () => {
        const modules = await Promise.all([
            import('@fontsource/source-serif-4/latin-400.css?inline'),
            import('@fontsource/source-serif-4/latin-600.css?inline'),
            import('@fontsource/source-serif-4/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "libre-baskerville": async () => {
        const modules = await Promise.all([
            import('@fontsource/libre-baskerville/latin-400.css?inline'),
            import('@fontsource/libre-baskerville/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "cormorant-garamond": async () => {
        const modules = await Promise.all([
            import('@fontsource/cormorant-garamond/latin-400.css?inline'),
            import('@fontsource/cormorant-garamond/latin-600.css?inline'),
            import('@fontsource/cormorant-garamond/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "eb-garamond": async () => {
        const modules = await Promise.all([
            import('@fontsource/eb-garamond/latin-400.css?inline'),
            import('@fontsource/eb-garamond/latin-600.css?inline'),
            import('@fontsource/eb-garamond/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "crimson-pro": async () => {
        const modules = await Promise.all([
            import('@fontsource/crimson-pro/latin-400.css?inline'),
            import('@fontsource/crimson-pro/latin-600.css?inline'),
            import('@fontsource/crimson-pro/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "literata": async () => {
        const modules = await Promise.all([
            import('@fontsource/literata/latin-400.css?inline'),
            import('@fontsource/literata/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "fraunces": async () => {
        const modules = await Promise.all([
            import('@fontsource/fraunces/latin-400.css?inline'),
            import('@fontsource/fraunces/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "jetbrains-mono": async () => {
        const modules = await Promise.all([
            import('@fontsource/jetbrains-mono/latin-400.css?inline'),
            import('@fontsource/jetbrains-mono/latin-500.css?inline'),
            import('@fontsource/jetbrains-mono/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "fira-code": async () => {
        const modules = await Promise.all([
            import('@fontsource/fira-code/latin-400.css?inline'),
            import('@fontsource/fira-code/latin-500.css?inline'),
            import('@fontsource/fira-code/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "source-code-pro": async () => {
        const modules = await Promise.all([
            import('@fontsource/source-code-pro/latin-400.css?inline'),
            import('@fontsource/source-code-pro/latin-600.css?inline'),
            import('@fontsource/source-code-pro/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "ibm-plex-mono": async () => {
        const modules = await Promise.all([
            import('@fontsource/ibm-plex-mono/latin-400.css?inline'),
            import('@fontsource/ibm-plex-mono/latin-500.css?inline'),
            import('@fontsource/ibm-plex-mono/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "roboto-mono": async () => {
        const modules = await Promise.all([
            import('@fontsource/roboto-mono/latin-400.css?inline'),
            import('@fontsource/roboto-mono/latin-500.css?inline'),
            import('@fontsource/roboto-mono/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "space-mono": async () => {
        const modules = await Promise.all([
            import('@fontsource/space-mono/latin-400.css?inline'),
            import('@fontsource/space-mono/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "inconsolata": async () => {
        const modules = await Promise.all([
            import('@fontsource/inconsolata/latin-400.css?inline'),
            import('@fontsource/inconsolata/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "oswald": async () => {
        const modules = await Promise.all([
            import('@fontsource/oswald/latin-400.css?inline'),
            import('@fontsource/oswald/latin-500.css?inline'),
            import('@fontsource/oswald/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "bebas-neue": async () => {
        const modules = await Promise.all([
            import('@fontsource/bebas-neue/latin-400.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "anton": async () => {
        const modules = await Promise.all([
            import('@fontsource/anton/latin-400.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
    "archivo": async () => {
        const modules = await Promise.all([
            import('@fontsource/archivo/latin-400.css?inline'),
            import('@fontsource/archivo/latin-600.css?inline'),
            import('@fontsource/archivo/latin-700.css?inline'),
        ]);
        return modules
            .map((mod) => (typeof mod === 'string' ? mod : (mod?.default ?? '')))
            .filter(Boolean)
            .join('\n');
    },
};
