/**
 * Save/export payload assembly.
 */

import { detachTopDropSpacerForExport, restoreTopDropSpacerAfterExport } from '../canvas-block-drag.js';
import { detachInnerDropSlotsForExport } from '../inner-drop-slots.js';
import { syncBindingsForExport, syncRepeatBindingsForExport } from '../bindings-ui.js';
import { syncAnimatedCountersForExport } from '../editor-animated-blocks.js';
import {
    ensureComponentInstancesForExport,
    syncComponentInstancePaintForExport,
    syncComponentInstancesForExport,
} from '../components-ui.js';
import { syncConditionsForExport } from '../conditions-ui.js';
import { findPageContentSlotInEditor } from '../chrome-content-slot-utils.js';
import { purgeOrphanPageContentNodes } from '../page-content-orphans.js';
import { extractChromeLayoutHtml } from '../editor-chrome-layout.js';
import { ensureCtaButtonsForExport } from '../editor-button-link.js';
import { ensureIconsForExport } from '../editor-utility-blocks.js';
import { ensureLayoutContainersForExport } from '../layout-blocks.js';
import { restoreContentWidthFromAttributes } from '../content-width-toolbar.js';
import { extractChromeShellPageHtml } from '../editor-chrome-shell.js';
import { applyVideoFacadesToExportedHtml, syncVideoComponentsForExport } from '../editor-video.js';
import {
    pruneEmptyDynamicBlocks,
    syncDynamicBlockAttributes,
} from '../plugins/voodbuilder-editor.js';
import { syncSiteHeaderConfig } from '../chrome/blocks/nav/config.js';
import { syncSiteFooterConfig } from '../chrome/blocks/footer/config.js';
import { isFooterBlock, isNavBlock } from '../chrome/ids.js';
import {
    bakeAuthorStylesToComposerForExport,
    bakeSvgPaintForExport,
    pruneRedundantSpacingZerosForExport,
    purgeDesyncedBackgroundCssRules,
    restoreSvgPaintInspectorStyle,
    restoreSvgPaintInspectorStyles,
    safeFindComponents,
    syncPaintStylesForExport,
    syncSpacingStylesForExport,
} from '../tailwind-visual-style.js';
import { shouldOmitAuthorStyleValue } from '../theme-tokens.js';

/**
 * GrapesJS private style classes (c1234) must not be persisted — clones share
 * those names and reloading makes sibling fonts/colors converge.
 *
 * @param {string} className
 * @returns {boolean}
 */
function isGrapesPrivateClassName(className) {
    return /^c\d+[a-z0-9]*$/i.test(String(className ?? '').trim());
}

/**
 * Mirror EditorPastedComponentNormalizer::isTailwindUtilityClassName — utilities
 * are regenerated by page JIT; only custom / #id author rules need persistence.
 *
 * @param {string} className
 * @returns {boolean}
 */
function isTailwindUtilityClassName(className) {
    const name = String(className ?? '').trim().replace(/^!/, '');

    if (name === '') {
        return false;
    }

    if (isGrapesPrivateClassName(name)) {
        return true;
    }

    // Bare utilities (no hyphen) that Tailwind ships as single tokens.
    if (/^(isolate|border|rounded|shadow|truncate|uppercase|lowercase|capitalize|italic|underline|antialiased|contents|grow|shrink)$/i.test(name)) {
        return true;
    }

    return /^(?:[a-z][a-z0-9_-]*:)*-?(?:flex|grid|inline-flex|inline|block|hidden|contents|table|flow-root|list-item|absolute|relative|fixed|sticky|static|container|mx-|my-|mt-|mb-|ml-|mr-|w-|h-|min-w-|max-w-|min-h-|max-h-|size-|gap-|p-|px-|py-|pt-|pb-|pl-|pr-|m-|text-|bg-|rounded|shadow|aspect-|col-|row-|items-|justify-|self-|order-|space-|divide-|border-opacity|border-|ring-|outline-|opacity-|z-|top-|bottom-|left-|right-|inset-|object-|overflow-|truncate|whitespace-|leading-|font-|tracking-|underline|decoration-|backdrop-|transition|duration-|ease-|scale-|rotate-|translate-|skew-|origin-|fill-|stroke-|sr-only|not-sr-only|pointer-events-|select-|cursor-|align-|place-|content-|grow|shrink|basis-|from-|to-|via-|bg-vp-|text-vp-|antialiased|subpixel-antialiased|italic|not-italic|visible|invisible|collapse|isolate|box-|break-|hyphens-|list-|columns-|float-|clear-|overscroll-|scroll-|snap-|touch-|will-change-|accent-|caret-|field-sizing-|animate-)/i
        .test(name);
}

/**
 * Keep Style Manager author paints (#id) and custom class rules from Library
 * / pasted embeds (e.g. .vb-hero-plasma__orb). Drop Tailwind utilities and
 * Grapes private classes — regenerated or harmful on reload.
 *
 * @param {string} selectors
 * @returns {boolean}
 */
function isAuthorStyleSelector(selectors) {
    const value = String(selectors ?? '').trim();

    if (value === '') {
        return false;
    }

    if (value.includes('#')) {
        return true;
    }

    if (! value.includes('.')) {
        return false;
    }

    const classMatches = value.matchAll(/\.((?:\\.|[^\s.#:[>+~,])+)/g);

    for (const match of classMatches) {
        const className = String(match[1] ?? '').replace(/\\/g, '').replace(/^!/, '');

        if (className !== '' && ! isTailwindUtilityClassName(className)) {
            return true;
        }
    }

    return false;
}

/**
 * Extract @keyframes blocks (nested braces) so Library/embed animations survive save.
 * Theme / Style Manager presets (fade-up, flip-up, ping, …) are NOT persisted — they
 * live in theme.css via Tailwind CSS Animated and must stay class-driven.
 *
 * @param {string} css
 * @returns {{ keyframes: string[], remainder: string }}
 */
function extractKeyframesBlocks(css) {
    const source = String(css ?? '');
    const keyframes = [];
    let remainder = '';
    let i = 0;

    while (i < source.length) {
        const at = source.slice(i).search(/@keyframes\b/i);

        if (at < 0) {
            remainder += source.slice(i);
            break;
        }

        remainder += source.slice(i, i + at);
        i += at;

        const brace = source.indexOf('{', i);

        if (brace < 0) {
            remainder += source.slice(i);
            break;
        }

        let depth = 0;
        let end = brace;

        for (; end < source.length; end += 1) {
            const ch = source[end];

            if (ch === '{') {
                depth += 1;
            } else if (ch === '}') {
                depth -= 1;

                if (depth === 0) {
                    end += 1;
                    break;
                }
            }
        }

        const block = source.slice(i, end).trim();

        if (block !== '' && ! isThemeAnimationKeyframeBlock(block)) {
            keyframes.push(block);
        }

        i = end;
    }

    return { keyframes, remainder };
}

/**
 * @keyframes shipped by tailwindcss-animated / Style Manager presets.
 * Custom Library motion (e.g. vb-plasma-spin) must still be persisted.
 *
 * @param {string} block
 * @returns {boolean}
 */
export function isThemeAnimationKeyframeBlock(block) {
    const match = String(block ?? '').match(/@keyframes\s+([^\s*{]+)/i);

    if (! match) {
        return false;
    }

    const name = String(match[1] ?? '').trim().toLowerCase();

    return /^(?:fade|fade-up|fade-down|fade-left|fade-right|flip-up|flip-down|ping|bounce|spin|pulse|wiggle|wiggle-more|shake|jump|jump-in|jump-out|rotate-x|rotate-y)$/.test(name);
}

export function extractGrapesComposerCss(css) {
    const source = String(css ?? '').trim();

    if (source === '') {
        return '';
    }

    const { keyframes, remainder } = extractKeyframesBlocks(source);

    // Strip @media blocks (utilities / responsive bundles are regenerated server-side).
    // prefers-reduced-motion for catalog motion lives in theme.css.
    let withoutMedia = remainder;
    let guard = 0;

    while (guard < 50) {
        const next = withoutMedia.replace(/@media[^{]*\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}/g, ' ');

        if (next === withoutMedia) {
            break;
        }

        withoutMedia = next;
        guard += 1;
    }

    const kept = [...keyframes];

    for (const match of withoutMedia.matchAll(/([^{}@]+)\{([^{}]*)\}/g)) {
        const selectors = match[1].trim();
        const body = match[2].trim();

        if (selectors === '' || body === '') {
            continue;
        }

        if (! isAuthorStyleSelector(selectors)) {
            continue;
        }

        const cleanedBody = sanitizeClearedPaintRuleBody(body);

        if (cleanedBody === '') {
            continue;
        }

        kept.push(`${selectors} {${cleanedBody}}`);
    }

    return kept.join('\n');
}

/**
 * Remove cleared SVG paint declarations (color/stroke/fill:none) from a CSS rule body.
 *
 * @param {string} body
 * @returns {string}
 */
export function sanitizeClearedPaintRuleBody(body) {
    return String(body ?? '')
        .split(';')
        .map((chunk) => chunk.trim())
        .filter((chunk) => {
            if (chunk === '') {
                return false;
            }

            const colon = chunk.indexOf(':');

            if (colon === -1) {
                return true;
            }

            const property = chunk.slice(0, colon).trim().toLowerCase();
            const value = chunk.slice(colon + 1).trim();

            if (! ['color', 'fill', 'stroke'].includes(property)) {
                return true;
            }

            return ! shouldOmitAuthorStyleValue(property, value);
        })
        .join('; ');
}

/**
 * Remove author `#id { … }` rules from a CSS blob (e.g. live JIT sheet).
 * Keeps utilities; avoids stale font-family #id rules overriding the canvas
 * after Save when the live sheet is injected last in the iframe head.
 *
 * @param {string} css
 * @returns {string}
 */
export function stripAuthorIdRules(css) {
    const source = String(css ?? '');

    if (source === '' || ! source.includes('#')) {
        return source.trim();
    }

    return source
        .replace(/#[A-Za-z][\w-]*(?:\s*,\s*#[A-Za-z][\w-]*)*\s*\{[^{}]*\}/g, ' ')
        .replace(/\n{3,}/g, '\n\n')
        .trim();
}

/**
 * Safety net: emit `#id { … }` rules from component inline + CssComposer #id
 * styles. Grapes `getCss()` can omit unused/private rules; without this, Style
 * Manager paints vanish from builder_payload.css on chrome-shell save.
 *
 * @param {object} editor
 * @returns {string}
 */
export function collectAuthorIdCssFromComponents(editor) {
    const wrapper = editor?.getWrapper?.();
    const cssApi = editor?.Css;

    if (! wrapper?.onAll) {
        return '';
    }

    const rules = [];
    const seen = new Set();

    wrapper.onAll((component) => {
        const id = String(component?.getId?.() ?? '').trim();

        if (id === '' || seen.has(id)) {
            return;
        }

        seen.add(id);

        const fromId = { ...(cssApi?.getIdRule?.(id)?.getStyle?.() ?? {}) };
        const inline = { ...(component.getStyle?.({ inline: true }) ?? {}) };
        // Combined getStyle() can include private-class paints still attached.
        const combined = { ...(component.getStyle?.() ?? {}) };
        const merged = { ...fromId, ...combined, ...inline };
        const decls = [];

        for (const [property, value] of Object.entries(merged)) {
            if (value == null || value === '') {
                continue;
            }

            const raw = String(value).trim();

            if (raw === '' || raw === 'undefined' || raw === 'null') {
                continue;
            }

            // Skip Grapes internal / empty clears / SM-invented defaults.
            if (/^(none|transparent|initial|inherit|unset)$/i.test(raw.replace(/\s*!important\s*$/i, '').trim())
                && (property === 'background' || property === 'background-color' || property === 'background-image')) {
                continue;
            }

            if (shouldOmitAuthorStyleValue(property, raw)) {
                continue;
            }

            decls.push(`${property}:${raw}`);
        }

        if (decls.length === 0) {
            return;
        }

        rules.push(`#${id} {${decls.join(';')}}`);
    });

    return rules.join('\n');
}

/**
 * Read Grapes CssComposer CSS, preferring keepUnusedStyles so #id paints that
 * are not referenced as classes still serialize.
 *
 * @param {object} editor
 * @returns {string}
 */
export function readComposerCssForPersist(editor) {
    if (typeof editor?.getCss !== 'function') {
        return '';
    }

    try {
        const withUnused = editor.getCss({ keepUnusedStyles: true });

        if (typeof withUnused === 'string' && withUnused.trim() !== '') {
            return withUnused.trim();
        }
    } catch {
        // Older Grapes builds may not accept options.
    }

    return String(editor.getCss() ?? '').trim();
}

/**
 * Merge CSS chunks, preferring the first declaration block per `#id` selector
 * (later duplicates from live/composer are skipped).
 *
 * @param {string[]} chunks
 * @returns {string}
 */
export function mergeAuthorCssChunks(chunks) {
    const seenIds = new Set();
    const out = [];

    for (const chunk of chunks) {
        const source = String(chunk ?? '').trim();

        if (source === '') {
            continue;
        }

        // Split into rules while keeping non-# utility blobs intact.
        if (! source.includes('#')) {
            if (! out.includes(source)) {
                out.push(source);
            }

            continue;
        }

        let cursor = 0;
        const re = /([^{}@]+)\{([^{}]*)\}/g;
        let match;

        while ((match = re.exec(source)) !== null) {
            const between = source.slice(cursor, match.index).trim();

            if (between !== '' && ! out.includes(between)) {
                out.push(between);
            }

            cursor = match.index + match[0].length;
            const selectors = match[1].trim();
            const body = match[2].trim();
            const rule = `${selectors} {${body}}`;

            if (selectors.includes('#')) {
                const ids = [...selectors.matchAll(/#([A-Za-z][\w-]*)/g)].map((m) => m[1]);
                const already = ids.some((id) => seenIds.has(id));

                if (already) {
                    continue;
                }

                ids.forEach((id) => seenIds.add(id));
            }

            out.push(rule);
        }

        const tail = source.slice(cursor).trim();

        if (tail !== '' && ! out.includes(tail)) {
            out.push(tail);
        }
    }

    return out.join('\n');
}

function normalizeDynamicBlockComponents(editor) {
    safeFindComponents(editor.getWrapper?.(), '[data-voodbuilder-block]').forEach((component) => {
        syncDynamicBlockAttributes(component);

        const blockId = component.getAttributes()['data-voodbuilder-block'];

        if (isNavBlock(blockId)) {
            syncSiteHeaderConfig(component);
        }

        if (isFooterBlock(blockId)) {
            syncSiteFooterConfig(component);
        }
    });
}

/**
 * Editor getHtml({ withProps: true }) serializes object props as
 * data-gjs-resizable="{"ratioDefault":1}" which is invalid HTML and leaks
 * junk onto the published page. Prefer single-quoted JSON attributes.
 *
 * @param {string} html
 * @returns {string}
 */
export function encodeJsonDataGjsAttributes(html) {
    if (typeof html !== 'string' || html === '' || ! html.includes('data-gjs-')) {
        return html;
    }

    return html.replace(
        /\s+data-gjs-([a-zA-Z0-9_-]+)="(\{[\s\S]*?\})"/g,
        (match, name, json) => {
            if (! json.includes('"')) {
                return match;
            }

            return ` data-gjs-${name}='${json.replace(/'/g, '&#39;')}'`;
        },
    );
}

/**
 * @param {object} editor
 * @param {{ mutate?: boolean }} [options]
 *   mutate=false → read-only snapshot for onUpdate (must not wipe CssComposer / styles).
 *   mutate=true (default) → save path: sync/bake/purge then serialize.
 */
export function buildPayload(editor, options = {}) {
    const mutate = options.mutate !== false;

    const runExportStep = (label, step) => {
        try {
            step();
        } catch (error) {
            console.warn(`Voodbuilder buildPayload: ${label} failed`, error);
        }
    };

    if (mutate) {
        runExportStep('detachReadingPreview', () => editor.trigger?.('voodbuilder:reading-preview:detach'));
        runExportStep('normalizeDynamicBlockComponents', () => normalizeDynamicBlockComponents(editor));
        runExportStep('pruneEmptyDynamicBlocks', () => pruneEmptyDynamicBlocks(editor));
        runExportStep('syncBindingsForExport', () => syncBindingsForExport(editor));
        runExportStep('ensureComponentInstancesForExport', () => ensureComponentInstancesForExport(editor));
        runExportStep('purgeDesyncedBackgroundCssRules', () => purgeDesyncedBackgroundCssRules(editor));
        runExportStep('syncSpacingStylesForExport', () => syncSpacingStylesForExport(editor));
        runExportStep('syncPaintStylesForExport', () => syncPaintStylesForExport(editor));
        // Persist Style Manager paints into #id CssComposer rules (and keep inline).
        runExportStep('bakeAuthorStylesToComposerForExport', () => bakeAuthorStylesToComposerForExport(editor));
        runExportStep('syncComponentInstancePaintForExport', () => syncComponentInstancePaintForExport(editor));
        runExportStep('bakeSvgPaintForExport', () => bakeSvgPaintForExport(editor));
        runExportStep('pruneRedundantSpacingZerosForExport', () => pruneRedundantSpacingZerosForExport(editor));
        runExportStep('syncComponentInstancesForExport', () => syncComponentInstancesForExport(editor));
        runExportStep('syncRepeatBindingsForExport', () => syncRepeatBindingsForExport(editor));
        runExportStep('syncAnimatedCountersForExport', () => syncAnimatedCountersForExport(editor));
        runExportStep('syncConditionsForExport', () => syncConditionsForExport(editor));
        runExportStep('syncVideoComponentsForExport', () => syncVideoComponentsForExport(editor));
        runExportStep('purgeOrphanPageContentNodes', () => {
            const slot = findPageContentSlotInEditor(editor);

            if (slot) {
                purgeOrphanPageContentNodes(slot);
            }
        });
        runExportStep('detachTopDropSpacerForExport', () => detachTopDropSpacerForExport(editor));
        runExportStep('detachInnerDropSlotsForExport', () => detachInnerDropSlotsForExport(editor));
        runExportStep('ensureCtaButtonsForExport', () => ensureCtaButtonsForExport(editor));
        runExportStep('ensureIconsForExport', () => ensureIconsForExport(editor));
        runExportStep('ensureLayoutContainersForExport', () => ensureLayoutContainersForExport(editor));
        runExportStep('restoreContentWidthFromAttributes', () => restoreContentWidthFromAttributes(editor));
        // Final bake after other syncs may have touched styles.
        runExportStep('bakeAuthorStylesToComposerForExport:final', () => bakeAuthorStylesToComposerForExport(editor));
    }

    let html;

    try {
        html = editor.getHtml({
            cleanId: false,
            // withProps:true calls Component.toJSON() for every node (full subtree each
            // time) — on large pasted pages that overflows the call stack. Server
            // normalizePayload already strips data-gjs-* anyway.
            withProps: false,
            keepInlineStyle: true,
        });
    } catch (error) {
        console.error('VoodBuilder getHtml failed; retrying without inline style opts', error);
        html = editor.getHtml();
    }

    if (editor.__voodbuilderChromeShellMode) {
        const slotHtml = extractChromeShellPageHtml(editor);

        if (slotHtml !== null) {
            const trimmed = slotHtml.trim();

            // Never wipe page content when the slot still has Grapes children but
            // serialization returned an empty string (regression that blanked Home).
            if (trimmed !== '') {
                html = slotHtml;
            } else {
                const childCount = findPageContentSlotInEditor(editor)?.components?.()?.length ?? 0;

                if (childCount === 0) {
                    // Author cleared the page content slot — empty save is intentional.
                    html = '';
                } else {
                    console.error(
                        'VoodBuilder: chrome shell HTML extract was empty while the content slot still has children — keeping full canvas HTML for server strip.',
                        { childCount },
                    );
                    // Keep `html` from getHtml(); server stripSiteChromeFromPageHtml removes chrome.
                }
            }
        }
    }

    if (editor.__voodbuilderChromeLayoutMode) {
        html = extractChromeLayoutHtml(editor);
    }

    // Click-to-play cover must survive export (GrapesJS still serializes embed iframes).
    html = applyVideoFacadesToExportedHtml(editor, html);

    html = encodeJsonDataGjsAttributes(html);

    // Intentionally empty page content must persist (delete-all / remove last block).
    // Do NOT restore __voodbuilderLastSavedPageHtml here — that blocked deletes from
    // reaching the front while the editor looked cleared.
    editor.__voodbuilderLastSavedPageHtml = String(html);
    // Chrome shell/layout: persist Style Manager paints from every reliable source:
    // 1) CssComposer #id rules (after bake / promote)
    // 2) component inline + #id walk (safety net if getCss omits unused rules)
    // 3) any #id still sitting in the live JIT sheet
    // Utilities come from the live sheet with #id stripped (strip only for that chunk).
    // Never strip #id from the *persisted* payload — that wiped fonts/colors on reload.
    const liveCssRaw = String(editor.__voodbuilderPageLiveCss ?? '').trim();
    const liveCssUtilities = stripAuthorIdRules(liveCssRaw);
    const liveCssAuthorIds = extractGrapesComposerCss(liveCssRaw);
    const composerCss = readComposerCssForPersist(editor);
    const styleManagerCss = extractGrapesComposerCss(composerCss);
    const componentAuthorCss = collectAuthorIdCssFromComponents(editor);
    const preferComposerSubset = Boolean(
        editor.__voodbuilderChromeShellMode || editor.__voodbuilderChromeLayoutMode,
    );
    const css = preferComposerSubset
        ? mergeAuthorCssChunks([styleManagerCss, componentAuthorCss, liveCssAuthorIds, liveCssUtilities])
        : mergeAuthorCssChunks([composerCss, componentAuthorCss, liveCssRaw]);

    const payload = {
        html,
        css,
        js: editor.getJs(),
    };

    if (editor.__voodbuilderChromeLayoutMode && editor.__voodbuilderReadingTypography) {
        payload.readingTypography = {
            font: editor.__voodbuilderReadingTypography.font,
            sidebarFont: editor.__voodbuilderReadingTypography.sidebarFont,
            size: editor.__voodbuilderReadingTypography.size,
            typeScale: editor.__voodbuilderReadingTypography.typeScale,
            sidebarTypeScale: editor.__voodbuilderReadingTypography.sidebarTypeScale,
        };
    }

    restoreTopDropSpacerAfterExport(editor);

    if (mutate) {
        runExportStep('attachReadingPreview', () => editor.trigger?.('voodbuilder:reading-preview:attach'));
    }

    restoreSvgPaintInspectorStyles(editor);

    const selected = editor.getSelected?.();

    if (selected && String(selected.get?.('tagName') ?? '').toLowerCase() === 'svg') {
        window.requestAnimationFrame(() => {
            restoreSvgPaintInspectorStyle(selected);
            editor.StyleManager?.select?.(selected);
        });
    }

    return payload;
}
