name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, sqlite3, mbstring
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist
        working-directory: .

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml.dist
